endpoints:
  common:
    common-platform-accounting-gl: https://app-common-platform-accounting-gl.dev.soon.es
    common-platform-auth-mgmt: https://app-common-platform-auth-mgmt.dev.soon.es
    common-platform-config-mgmt: https://app-common-platform-config-mgmt.dev.soon.es
    common-platform-contract-mgmt: https://app-common-platform-contract-mgmt.dev.soon.es
    common-platform-customer-mgmt: https://app-common-platform-customer-mgmt.dev.soon.es
    common-platform-distributor-mgmt: https://app-common-platform-distributor-mgmt.dev.soon.es
    common-platform-document-mgmt: https://app-common-platform-document-mgmt.dev.soon.es
    common-platform-kycb-mgmt: https://app-common-platform-kycb-mgmt.dev.soon.es
    common-platform-modelhub: https://app-common-platform-modelhub.dev.soon.es
    common-platform-notification-services: https://app-common-platform-notification-services.dev.soon.es
    common-platform-org-mgmt: https://app-common-platform-org-mgmt.dev.soon.es
    common-platform-product-mgmt: https://app-common-platform-product-mgmt.dev.soon.es
    common-platform-reference-master-data: https://app-common-platform-reference-master-data.dev.soon.es
    common-platform-rule-engine: https://app-common-platform-rule-engine.dev.soon.es
    common-platform-sca-mgmt: https://app-common-platform-sca-mgmt.dev.soon.es
    common-platform-user-mgmt: https://app-common-platform-user-mgmt.dev.soon.es
    common-platform-webhooks: https://app-common-platform-webhooks.dev.soon.es

  core:
    core-baking-cards: https://app-core-baking-cards.dev.soon.es
    core-banking-accounts: https://app-core-banking-accounts.dev.soon.es
    core-banking-card-transaction-authorization-center: https://app-core-banking-card-transaction-authorization-center.dev.soon.es
    core-banking-cards: https://app-core-banking-cards.dev.soon.es
    core-banking-ledger: https://app-core-banking-ledger.dev.soon.es
    core-banking-payment-hub: https://app-core-banking-payment-hub.dev.soon.es
    core-banking-payments: https://app-core-banking-payments.dev.soon.es
    core-banking-psdx: https://app-core-banking-psdx.dev.soon.es
    core-erp-accounting-mgmt: https://app-core-erp-accounting-mgmt.dev.soon.es
    core-erp-compliance-mgmt: https://app-core-erp-compliance-mgmt.dev.soon.es
    core-erp-crm-mgmt: https://app-core-erp-crm-mgmt.dev.soon.es
    core-erp-inventory-mgmt: https://app-core-erp-inventory-mgmt.dev.soon.es
    core-erp-logistic-mgmt: https://app-core-erp-logistic-mgmt.dev.soon.es
    core-erp-master-data-mgmt: https://app-core-erp-master-data-mgmt.dev.soon.es
    core-erp-purchasing-mgmt: https://app-core-erp-purchasing-mgmt.dev.soon.es
    core-erp-sales-mgmt: https://app-core-erp-sales-mgmt.dev.soon.es
    core-lending-collateral-management: https://app-core-lending-collateral-management.dev.soon.es
    core-lending-confirming: https://app-core-lending-confirming.dev.soon.es
    core-lending-credit-cards: https://app-core-lending-credit-cards.dev.soon.es
    core-lending-credit-scoring: https://app-core-lending-credit-scoring.dev.soon.es
    core-lending-delinquency-collections: https://app-core-lending-delinquency-collections.dev.soon.es
    core-lending-factoring: https://app-core-lending-factoring.dev.soon.es
    core-lending-leasing: https://app-core-lending-leasing.dev.soon.es
    core-lending-loan-origination: https://app-core-lending-loan-origination.dev.soon.es
    core-lending-loan-servicing: https://app-core-lending-loan-servicing.dev.soon.es
    core-lending-mortgage: https://app-core-lending-mortgage.dev.soon.es
    core-lending-provisioning-risk: https://app-core-lending-provisioning-risk.dev.soon.es
    core-lending-regulatory-compliance: https://app-core-lending-regulatory-compliance.dev.soon.es
    core-lending-renting: https://app-core-lending-renting.dev.soon.es
    core-orchestrator: https://app-core-orchestrator.dev.soon.es

  domain:
    accounts-payments-domain-charges: https://app-accounts-payments-domain-charges.dev.soon.es
    accounts-payments-domain-clearing-switch: https://app-accounts-payments-domain-clearing-switch.dev.soon.es
    accounts-payments-domain-gateways: https://app-accounts-payments-domain-gateways.dev.soon.es
    accounts-payments-domain-initiation: https://app-accounts-payments-domain-initiation.dev.soon.es
    accounts-payments-domain-issuing-cards: https://app-accounts-payments-domain-issuing-cards.dev.soon.es
    accounts-payments-domain-ledger: https://app-accounts-payments-domain-ledger.dev.soon.es
    accounts-payments-domain-remittance-payouts: https://app-accounts-payments-domain-remittance-payouts.dev.soon.es
    accounts-payments-domain-standing-orders: https://app-accounts-payments-domain-standing-orders.dev.soon.es
    accounts-payments-domain-tokens: https://app-accounts-payments-domain-tokens.dev.soon.es
    accounts-payments-domain-transactions-engine: https://app-accounts-payments-domain-transactions-engine.dev.soon.es
    customer-domain-aml-ctf: https://app-customer-domain-aml-ctf.dev.soon.es
    customer-domain-cases-complaints: https://app-customer-domain-cases-complaints.dev.soon.es
    customer-domain-consents: https://app-customer-domain-consents.dev.soon.es
    customer-domain-contracts: https://app-customer-domain-contracts.dev.soon.es
    customer-domain-docs-attachments: https://app-customer-domain-docs-attachments.dev.soon.es
    customer-domain-kyc-kyb: https://app-customer-domain-kyc-kyb.dev.soon.es
    customer-domain-people: https://app-customer-domain-people.dev.soon.es
    customer-domain-ubo-registry: https://app-customer-domain-ubo-registry.dev.soon.es
    distributor-domain-agents: https://app-distributor-domain-agents.dev.soon.es
    distributor-domain-branding: https://app-distributor-domain-branding.dev.soon.es
    distributor-domain-catalog: https://app-distributor-domain-catalog.dev.soon.es
    distributor-domain-partner-settlement: https://app-distributor-domain-partner-settlement.dev.soon.es
    distributor-domain-pipeline: https://app-distributor-domain-pipeline.dev.soon.es
    lending-domain-loan-origination: https://app-lending-domain-loan-origination.dev.soon.es
    lending-domain-loan-servicing: https://app-lending-domain-loan-servicing.dev.soon.es
    organization-domain-branches: https://app-organization-domain-branches.dev.soon.es
    organization-domain-channels: https://app-organization-domain-channels.dev.soon.es
    organization-domain-employees: https://app-organization-domain-employees.dev.soon.es
    organization-domain-positions: https://app-organization-domain-positions.dev.soon.es
    organization-domain-roles: https://app-organization-domain-roles.dev.soon.es
    product-domain-accounts-deposits: https://app-product-domain-accounts-deposits.dev.soon.es
    product-domain-cards: https://app-product-domain-cards.dev.soon.es
    product-domain-lending: https://app-product-domain-lending.dev.soon.es
    product-domain-pricing: https://app-product-domain-pricing.dev.soon.es
    product-domain-product-catalog: https://app-product-domain-product-catalog.dev.soon.es
    product-domain-trade-finance: https://app-product-domain-trade-finance.dev.soon.es
    reporting-data-domain-api-surface: https://app-reporting-data-domain-api-surface.dev.soon.es
    reporting-data-domain-audit-trail-observability: https://app-reporting-data-domain-audit-trail-observability.dev.soon.es
    reporting-data-domain-common-model: https://app-reporting-data-domain-common-model.dev.soon.es
    reporting-data-domain-telemetry: https://app-reporting-data-domain-telemetry.dev.soon.es
    treasury-finance-domain-alm-ftp: https://app-treasury-finance-domain-alm-ftp.dev.soon.es
    treasury-finance-domain-fx-rates-services: https://app-treasury-finance-domain-fx-rates-services.dev.soon.es
    treasury-finance-domain-gl-bi-bridge: https://app-treasury-finance-domain-gl-bi-bridge.dev.soon.es
    treasury-finance-domain-kpi-financials: https://app-treasury-finance-domain-kpi-financials.dev.soon.es
    treasury-finance-domain-liquidity-cash-mgmt: https://app-treasury-finance-domain-liquidity-cash-mgmt.dev.soon.es
    treasury-finance-domain-revenue-accounting: https://app-treasury-finance-domain-revenue-accounting.dev.soon.es
    treasury-finance-domain-risk-forecasting: https://app-treasury-finance-domain-risk-forecasting.dev.soon.es
    treasury-finance-domain-securities-stp: https://app-treasury-finance-domain-securities-stp.dev.soon.es